# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `cssbundling-rails` gem.
# Please instead update this file by running `bin/tapioca gem cssbundling-rails`.


# source://cssbundling-rails//lib/cssbundling-rails.rb#1
module Cssbundling; end

# source://cssbundling-rails//lib/cssbundling/engine.rb#2
class Cssbundling::Engine < ::Rails::Engine
  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

# source://cssbundling-rails//lib/cssbundling/version.rb#2
Cssbundling::VERSION = T.let(T.unsafe(nil), String)
