# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def add_llm_api_key_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def close_pr_tab_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def close_pr_tabs_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def dashboard_index_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def delete_llm_api_key_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def demo_login_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def direct_pr_review_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_source_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_registration_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_repository_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def open_pr_tabs_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def passwords_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def pull_request_review_llm_conversation_messages_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def pull_request_review_reset_conversation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def pull_request_review_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def pull_request_reviews_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_incinerate_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_reroute_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_sources_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailgun_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_postmark_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_relay_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_sendgrid_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def registrations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def repositories_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def repository_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reset_tabs_pull_request_reviews_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reset_tabs_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def select_tab_tabs_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def setting_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def show_by_details_pull_request_reviews_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sync_all_repositories_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sync_pull_request_review_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sync_repository_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_recede_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_refresh_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_resume_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_llm_api_key_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_llm_preferences_settings_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_url(*args); end
end
