# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ProcessLlmResponseJob`.
# Please instead update this file by running `bin/tapioca dsl ProcessLlmResponseJob`.


class ProcessLlmResponseJob
  class << self
    sig do
      params(
        pull_request_review_id: T.untyped,
        user_message_id: T.untyped,
        block: T.nilable(T.proc.params(job: ProcessLlmResponseJob).void)
      ).returns(T.any(ProcessLlmResponseJob, FalseClass))
    end
    def perform_later(pull_request_review_id, user_message_id, &block); end

    sig { params(pull_request_review_id: T.untyped, user_message_id: T.untyped).returns(T.untyped) }
    def perform_now(pull_request_review_id, user_message_id); end
  end
end
